# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Benjamin Crysler's Site
email: ben.crysler@cmich.edu
description: > # this means to ignore newlines until "baseurl:"
  The purpose of this site is to display Benjamin Crysler's work on his tech
  projects. All projects utilize both original and borrowed open-source code,
  in which case sources will be acknowledged. Enjoy!
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://benjamincrysler.com" # the base hostname & protocol for your site
twitter_username: bendcrysler
github_username:  bendcrysler

# Build settings
markdown: kramdown
